/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("BooksObjectPageObjectPage journey");

        opaTest("Navigate to BooksObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheBooksListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheBooksListGenerated.onTable().iCheckRows();
            When.onTheBooksListGenerated.onTable().iPressRow(0);

            Then.onTheBooksObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check the number of sections of the Object Page", function (_Given, _When, Then) {
            Then.onTheBooksObjectPageGenerated.iCheckNumberOfSections(3);
        });

        opaTest("Check the GeneratedFacet1 section of the Object Page", function (_Given, When, Then) {
            When.onTheBooksObjectPageGenerated.iGoToSection({ section: "GeneratedFacet1" });
            Then.onTheBooksObjectPageGenerated.iCheckSection({ section: "GeneratedFacet1" });
            Then.onTheBooksObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "genre" });
            Then.onTheBooksObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "publishedAt" });
            Then.onTheBooksObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "pages" });
            Then.onTheBooksObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "price" });
        });

        opaTest("Check the EntryInformation section of the Object Page", function (_Given, When, Then) {
            When.onTheBooksObjectPageGenerated.iGoToSection({ section: "EntryInformation" });
            Then.onTheBooksObjectPageGenerated.iCheckSection({ section: "EntryInformation" });
            Then.onTheBooksObjectPageGenerated.onForm({ section: "EntryInformation" }).iCheckField({ property: "createdBy" });
            Then.onTheBooksObjectPageGenerated.onForm({ section: "EntryInformation" }).iCheckField({ property: "createdAt" });
            Then.onTheBooksObjectPageGenerated.onForm({ section: "EntryInformation" }).iCheckField({ property: "modifiedAt" });
            Then.onTheBooksObjectPageGenerated.onForm({ section: "EntryInformation" }).iCheckField({ property: "modifiedBy" });
        });

        opaTest("Check the Chapters section of the Object Page", function (_Given, When, Then) {
            When.onTheBooksObjectPageGenerated.iGoToSection({ section: "Chapters" });
            Then.onTheBooksObjectPageGenerated.iCheckSection({ section: "Chapters" });
        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});